### ISSUE TITLE
[Authentication] Is Authentication the correct mechanism for specifying the ownership of a Thing? 

### ISSUE THREAD

**Issue by brentzundel** [w3c/did-core#22] opened 2019-09-20 06:40 UTC
@mwherman2000 moved from CCG (https://github.com/w3c-ccg/did-spec/issues/148)

**Comment by msporny** [comment] 2019-10-08 15:25
This may be a duplicate of issue #2.

**Comment by msporny** [comment] 2020-02-13 03:54
This issue will be closed soon unless there is an objection to the changes made to address the issue.

**Comment by msporny** [comment] 2020-02-21 03:51
The authentication section was expanded to address the issue raised. No further requests have been made to change the section. Closing.

**Closed by msporny** 2020-02-21 03:51 UTC
Labels: pending close
