### ISSUE TITLE
Is "verification method" relevant to inbound (as opposed to outbound) communication?

### ISSUE THREAD

**Issue by dhh1128** [w3c/did-core#276] opened 2020-05-11 23:17 UTC
The spec currently describes verification methods as follows:

>Verification methods "provide a set of mechanisms enabling a DID controller to prove control of the DID." (Abstract)

>Verification method: A set of parameters required to independently verify a proof, such as an identifier for a public/private key pair that would be used in the proof. (section 2)

Both of these explanations convey the idea that the DID controller is proving the legitimacy of an action to an outside audience. However, when we apply the notion of verification methods to the problem domain of general communication, some friction shows up. For example, how does Alice say that one or more of her keys are appropriate targets for encryption of __inbound__ communication (sent to her as opposed to emitted by her)?

We could create an item off the root of the DID doc called, for example, "readEncrypted", and Alice could define or reference there all the public keys that are usable as encryption targets when talking to her. Such an item would look and behave very much like a verification method block like "keyAgreement", but it wouldn't be a method for external parties to verify actions by Alice. If anything, it would be the opposite -- a method for Alice to verify that something from external parties was really intended for her. And we could explain this either by broadening the definition of "verification method" or by explaining the section as being like one for a verification method, but not fitting in the category.

Alternatively, we could say that "keyAgreement" is the right section to use for this, and make the assumption that the set of keys Alice uses to encrypt outbound is always exactly equal to the set of keys that Alice uses to decrypt inbound. This assumption is clearly not guaranteed to be true (a sensor could emit encrypted data on Alice's behalf, but be incapable of receiving anything; a sink could consume encrypted data inbound, but never emit anything) -- but perhaps it's close enough?

Generalizing still further, do we need to contemplate inbound actions in general, of which decryption is just a special case? If so, what do we call the mechanism for constraining or specifying or configuring them? "Verification method" feels a bit odd, if we take the concept that far. Something like "configuration method" might fit better.

I'm not necessarily arguing for the broader term, but I do need a way to specify inbound encryption keys, and I'd like the spec to use language that lets a mental model for such things to fit nicely.

**Comment by dhh1128** [comment] 2020-05-13 04:47
Cross-referencing #268

**Comment by dhh1128** [comment] 2020-05-13 21:12
Based on the resolution of [this issue](https://github.com/decentralized-identity/didcomm-messaging/pull/48#issuecomment-628204677) over in the DIDComm repo, I'm now comfortable using `keyAgreement` as the container for all the keys used to do DH and share symmetric keys for encryption in DIDComm. 

However, I still feel that our current terminology in the DID spec is not quite right. We want to describe things like "capabilityInvocation" and "keyAgreement" as "verification methods." I'm comfortable so far. But then we want to say that verification methods are "A set of parameters required to independently verify a proof, such as an identifier for a public/private key pair that would be used in the proof." That could be read broadly enough to cover what's happening in "keyAgreement," but I think such a reading is non-obvious. It might be better to provide a little more explanation.

Would anyone mind if I raised a PR to broaden the definition a bit?

**Comment by dlongley** [comment] 2020-05-13 21:23
> Would anyone mind if I raised a PR to broaden the definition a bit?

Not at all, I also think we should broaden a bit to help with the dissonance around "keyAgreement". I'm looking forward to seeing the exact language proposed. Btw, a slight clarification on your comments above: "capabilityInvocation"/"keyAgreement" are property names that are called "verification relationships" in the DID core spec and the values associated with them are the things that are called "verification methods".

**Comment by dhh1128** [comment] 2020-05-13 21:31
Thanks for the clarification of verbiage. That makes sense to me, and I'll try to use those terms accurately.

**Comment by dhh1128** [comment] 2020-05-13 22:00
Okay. PR raised: https://github.com/w3c/did-core/pull/284

**Comment by dhh1128** [comment] 2020-05-15 15:51
Now that there's a PR to discuss, I'm comfortable closing this issue. But I'm not aware of protocol: do I just do that, or does the group have to vote on it, or is there some other method for deciding the issue is adequately covered?

**Comment by brentzundel** [comment] 2020-05-15 16:29
We should leave it open until the PR that addresses the issue is merged.

**Comment by kdenhartog** [comment] 2020-05-17 12:44
Addressed in PR #284 closing.

**Closed by kdenhartog** 2020-05-17 12:44 UTC
Labels: PR exists
