### ISSUE TITLE
Remove uses of publicKeyHex 

### ISSUE THREAD

**Issue by selfissued** [w3c/did-core#280] opened 2020-05-12 03:01 UTC
Given the consensus to either use JWK, PEM, or Base58 encoded keys, keeping the publicKeyHex example only sows confusion and reduces interoperability.  We need to remove the uses of publicKeyHex from the specification.

**Comment by peacekeeper** [comment] 2020-05-12 08:01
We decided to allow PEM because that is the most common format for RSA keys. As discussed in the related issue https://github.com/w3c/did-core/issues/236, hex is the most common format for Bitcoin and Ethereum public keys.

Those who work on Bitcoin and Ethereum based DID method should weigh in on whether they prefer to use publicKeyHex (more natural in their community) or publicKeyBase58 (reducing optionality and choice).

**Comment by rhiaro** [comment] 2020-06-01 14:25
`publicKeyHex` only appears in [this example](https://w3c.github.io/did-core/#example-12-various-public-keys). I could PR to just remove it to resolve this issue, but I'm worried that would fork the discussion about it in #236 into the PR which would probably not be helpful. I'd like to suggest closing this issue as a duplicate of #236, with the promise that all examples will be audited for unspecified or inappropriate properties before the spec progresses. So if the discussion in #236 results in consensus on not wanting `publicKeyHex` in the core spec it will be removed then. Sound okay?

**Comment by peacekeeper** [comment] 2020-06-01 15:28
I agree with @rhiaro this should be closed as a duplicate of https://github.com/w3c/did-core/issues/236, and discussion/resolution should continue there.

**Comment by brentzundel** [comment] 2020-06-26 17:27
No comments since marked pending close, closing.

**Closed by brentzundel** 2020-06-26 17:27 UTC
Labels: editorial, pending close
