### ISSUE TITLE
Representations need explicit type conversion rules

### ISSUE THREAD

**Issue by jricher** [w3c/did-core#462] opened 2020-11-17 16:54 UTC
@msporny has the right of it, but it also needs to clearly go both ways, to and from the data model data types and the representation's data types. So you need things like this strawman:

"If you see an Integer in the ADM it goes in a JSON Number"

As well as:

"If you see a JSON Number in the representation, and don't have an additional property definition, it is an ADM Float".

I'm ok with this being in a separate PR but this can't be lost.

_Originally posted by @jricher in https://github.com/w3c/did-core/pull/455#discussion_r525283957_

**Comment by peacekeeper** [comment] 2020-11-17 17:02
This is related to https://github.com/w3c/did-core/issues/456 (value space vs. lexical space).

**Comment by OR13** [comment] 2020-12-12 18:18
@jricher @msporny @peacekeeper how can I take action on this issue?

feels like this is a duplicate of the concept of a "well defined" representation... if the representations production consumption rules don't solve this, how is it valid? if they do, why is this issue needed?

**Comment by msporny** [comment] 2020-12-12 18:39
> @jricher @msporny @peacekeeper how can I take action on this issue?

It is, and I'm actively working on this issue right now -- and #361 -- the last thing that needs to be done is CBOR consumption rules (getting ready to write that PR in the next 30 minutes).

@OR13 I reassigned this to me, will notify in this thread when I have a PR finished for it.

In short, I expect issue #462 and issue #361 to be closed when PR #476 is merged.

**Comment by msporny** [comment] 2020-12-14 16:21
PR #476 has been merged, closing this issue.

**Closed** 2020-12-14 16:21 UTC
Labels: pre-cr-p2
