### ISSUE TITLE
Move "resource=true" parameter from DID Core to the DID Spec Registries

### ISSUE THREAD

**Issue by jandrieu** [w3c/did-core#577] opened 2021-01-25 19:01 UTC
Per discussion on the special topic call. 

@msporny Offered to make a PR for this.

**Comment by msporny** [comment] 2021-01-25 21:00
@rhiaro beat both of us to it -- PR #572 moves the resource parameter out of the spec.

I believe that either @brentzundel or @talltree volunteered to write the PR for it.

**Comment by msporny** [comment] 2021-01-25 21:01
This issue will be closed once PR #572 is merged.

**Comment by brentzundel** [comment] 2021-01-25 23:15
This issue should not be closed until 'resource=true' is in DID Spec Registries.
I know that I did not volunteer to put it there.

**Comment by msporny** [comment] 2021-01-28 14:58
> This issue should not be closed until 'resource=true' is in DID Spec Registries.
> I know that I did not volunteer to put it there.

My bad... reassigning to @talltree -- this issue will be closed when PR #572 has been merged AND `resource=true` is moved to the DID Specification Registries OR when the group decides to enter CR.

@talltree, please write the DID Specification Registries extension for `resource=true` and get it into the DID Spec Registries.

**Comment by msporny** [comment] 2021-02-01 14:31
resource=true is now in the registries but with a dangling link to the specification that defines it. 

@brentzundel can we close this issue since it's in the registries now?

**Comment by rhiaro** [comment] 2021-02-01 14:46
I added a [corresponding issue on the DID Spec Registries](https://github.com/w3c/did-spec-registries/issues/244)

**Comment by msporny** [comment] 2021-02-11 00:30
@brentzundel confirmed that we can close this issue since the issue has been added to the DID Specification Registries.

**Closed** 2021-02-11 00:31 UTC
Labels: PR exists, pre-cr-p1
