### ISSUE TITLE
Why is versionTime at risk?

### ISSUE THREAD

**Issue by oed** [w3c/did-core#773] opened 2021-07-03 13:13 UTC
Looks like there is a handful of implementations of the `versionTime` query param: https://github.com/w3c/did-test-suite/search?q=versionTime

Yet it's still has the "FEATURE AT RISK" note: https://w3c.github.io/did-core/#did-parameters

**Comment by msporny** [comment] 2021-07-03 15:52
versionTime is no longer at risk, it has achieved the minimum number of implementations to keep it in the spec: https://w3c.github.io/did-test-suite/#spec-statement-summary

Those at-risk issue markers were manually added and they need to be manually removed. I'm delaying doing that until the end of CR because of the heavy workload that I'm under... removing at risk markers often come with discussions that are better had AFTER we come out of CR than while we're going through CR.

You are free to raise a PR removing the at risk marker for it (and anything else you can see as no longer at-risk).

**Comment by msporny** [comment] 2021-07-03 15:53
I'm marking this as `pending close` -- as the issue is effectively resolved once we come out of CR (because there are enough implementations now).

**Comment by msporny** [comment] 2021-07-11 18:08
As of the latest implementation report, `versionTime` is no longer at risk: https://lists.w3.org/Archives/Public/public-did-wg/2021Jul/0004.html

**Comment by msporny** [comment] 2021-07-11 19:53
PR #775 has been raised to address this issue. This issue will be closed once that PR has been merged.

**Comment by msporny** [comment] 2021-07-17 20:41
PR #775 has been merged, which addresses this issue (and @oed has confirmed that it addresses their concern). Closing.

**Closed** 2021-07-17 20:41 UTC
Labels: PR exists, cr-comment, cr-comment-resolved-implicit, pending close
